services:
    postgres_db:
        image: postgres:18-alpine
        container_name: tomcat-kafka_db
        env_file:
            - .env.dev
        ports:
            - "5432:5432"
        volumes:
            - tomcat-kafka_data:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    kafka:
        image: apache/kafka:4.1.1
        container_name: tomcat-kafka_kafka
        env_file:
            - .env.dev
        ports:
          - "9092:9092"
    java-app:
        build:
            context: ./java-backend
            dockerfile: Dockerfile.dev
        container_name: tomcat-kafka_app
        ports:
            - "8080:8080"
        volumes:
          - ./java-backend/api.jsp:/usr/local/tomcat/webapps/ROOT/api.jsp
        depends_on:
            - postgres_db
            - kafka

volumes:
    tomcat-kafka_data:
